# Generated by Django 2.2.16 on 2022-09-21 07:08

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. Can't be 'me'.", max_length=150, unique=True, validators=[users.validators.custom_username_validator, django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='username'),
        ),
    ]
